/*
 * Batchly.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using Batchly.PCL.Controllers;
using Batchly.PCL.Http.Client;

namespace Batchly.PCL
{
    public partial class BatchlyClient
    {

        /// <summary>
        /// Singleton access to TesseractApp controller
        /// </summary>
        public TesseractAppController TesseractApp
        {
            get
            {
                return Batchly.PCL.Controllers.TesseractAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SparkApp controller
        /// </summary>
        public SparkAppController SparkApp
        {
            get
            {
                return Batchly.PCL.Controllers.SparkAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Projects controller
        /// </summary>
        public ProjectsController Projects
        {
            get
            {
                return Batchly.PCL.Controllers.ProjectsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PrivateApp controller
        /// </summary>
        public PrivateAppController PrivateApp
        {
            get
            {
                return Batchly.PCL.Controllers.PrivateAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PigApp controller
        /// </summary>
        public PigAppController PigApp
        {
            get
            {
                return Batchly.PCL.Controllers.PigAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to JmeterApp controller
        /// </summary>
        public JmeterAppController JmeterApp
        {
            get
            {
                return Batchly.PCL.Controllers.JmeterAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ImageMagickApp controller
        /// </summary>
        public ImageMagickAppController ImageMagickApp
        {
            get
            {
                return Batchly.PCL.Controllers.ImageMagickAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to HiveApp controller
        /// </summary>
        public HiveAppController HiveApp
        {
            get
            {
                return Batchly.PCL.Controllers.HiveAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to HadoopStreamingApp controller
        /// </summary>
        public HadoopStreamingAppController HadoopStreamingApp
        {
            get
            {
                return Batchly.PCL.Controllers.HadoopStreamingAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to HadoopApp controller
        /// </summary>
        public HadoopAppController HadoopApp
        {
            get
            {
                return Batchly.PCL.Controllers.HadoopAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to FFmpegApp controller
        /// </summary>
        public FFmpegAppController FFmpegApp
        {
            get
            {
                return Batchly.PCL.Controllers.FFmpegAppController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Accounts controller
        /// </summary>
        public AccountsController Accounts
        {
            get
            {
                return Batchly.PCL.Controllers.AccountsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Runs controller
        /// </summary>
        public RunsController Runs
        {
            get
            {
                return Batchly.PCL.Controllers.RunsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Processors controller
        /// </summary>
        public ProcessorsController Processors
        {
            get
            {
                return Batchly.PCL.Controllers.ProcessorsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Jobs controller
        /// </summary>
        public JobsController Jobs
        {
            get
            {
                return Batchly.PCL.Controllers.JobsController.Instance;
            }
        }

        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Client constructor
        /// </summary>
        public BatchlyClient()
        {
            Configuration.LoadFromConfig();
        }

        public BatchlyClient(String baseUri, String apiKey, String apiSecret)
        {
            Configuration.BaseUri = baseUri;
            Configuration.ApiKey = apiKey;
            Configuration.ApiSecret = apiSecret;
        }
    }
}