/*
 * Batchly.Api
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Batchly.Api;

namespace Batchly.Api.Models
{
    public class AccountModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private double? activeProcessorCount;
        private double? activeProjectCount;
        private PlatformEnum? platform;
        private string platformName;
        private string baseRegion;
        private string id;
        private string name;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ActiveProcessorCount")]
        public double? ActiveProcessorCount 
        { 
            get 
            {
                return this.activeProcessorCount; 
            } 
            set 
            {
                this.activeProcessorCount = value;
                onPropertyChanged("ActiveProcessorCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ActiveProjectCount")]
        public double? ActiveProjectCount 
        { 
            get 
            {
                return this.activeProjectCount; 
            } 
            set 
            {
                this.activeProjectCount = value;
                onPropertyChanged("ActiveProjectCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Platform", ItemConverterType = typeof(StringValuedEnumConverter))]
        public PlatformEnum? Platform 
        { 
            get 
            {
                return this.platform; 
            } 
            set 
            {
                this.platform = value;
                onPropertyChanged("Platform");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PlatformName")]
        public string PlatformName 
        { 
            get 
            {
                return this.platformName; 
            } 
            set 
            {
                this.platformName = value;
                onPropertyChanged("PlatformName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BaseRegion")]
        public string BaseRegion 
        { 
            get 
            {
                return this.baseRegion; 
            } 
            set 
            {
                this.baseRegion = value;
                onPropertyChanged("BaseRegion");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 