/*
 * Batchly.Api
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Batchly.Api;

namespace Batchly.Api.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum PlatformEnum
    {
        NONE, //TODO: Write general description for this method
        AMAZONWEBSERVICES, //TODO: Write general description for this method
        MICROSOFTAZURE, //TODO: Write general description for this method
        GOOGLECOMPUTEENGINE, //TODO: Write general description for this method
        BOX, //TODO: Write general description for this method
        PORTICOR, //TODO: Write general description for this method
        AMAZONS3, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type PlatformEnum
    /// </summary>
    public static class PlatformEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "None", "AmazonWebServices", "MicrosoftAzure", "GoogleComputeEngine", "Box", "Porticor", "AmazonS3" };

        /// <summary>
        /// Converts a PlatformEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The PlatformEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(PlatformEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case PlatformEnum.NONE:
                case PlatformEnum.AMAZONWEBSERVICES:
                case PlatformEnum.MICROSOFTAZURE:
                case PlatformEnum.GOOGLECOMPUTEENGINE:
                case PlatformEnum.BOX:
                case PlatformEnum.PORTICOR:
                case PlatformEnum.AMAZONS3:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of PlatformEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of PlatformEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<PlatformEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into PlatformEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed PlatformEnum value</returns>
        public static PlatformEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type PlatformEnum", value));

            return (PlatformEnum) index;
        }
    }
} 