/*
 * Batchly.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Batchly.PCL;

namespace Batchly.PCL.Models
{
    public class ListRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string continuationToken;
        private List<Filter> filters;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContinuationToken")]
        public string ContinuationToken 
        { 
            get 
            {
                return this.continuationToken; 
            } 
            set 
            {
                this.continuationToken = value;
                onPropertyChanged("ContinuationToken");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Filters")]
        public List<Filter> Filters 
        { 
            get 
            {
                return this.filters; 
            } 
            set 
            {
                this.filters = value;
                onPropertyChanged("Filters");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 