/*
 * Batchly.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Batchly.PCL;

namespace Batchly.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum OperationEnum
    {
        NONE, //TODO: Write general description for this method
        LESSTHAN, //TODO: Write general description for this method
        GREATERTHAN, //TODO: Write general description for this method
        EQUALS, //TODO: Write general description for this method
        NOTEQUALS, //TODO: Write general description for this method
        IN, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type OperationEnum
    /// </summary>
    public static class OperationEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "None", "LessThan", "GreaterThan", "Equals", "NotEquals", "In" };

        /// <summary>
        /// Converts a OperationEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The OperationEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(OperationEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case OperationEnum.NONE:
                case OperationEnum.LESSTHAN:
                case OperationEnum.GREATERTHAN:
                case OperationEnum.EQUALS:
                case OperationEnum.NOTEQUALS:
                case OperationEnum.IN:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of OperationEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of OperationEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<OperationEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into OperationEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed OperationEnum value</returns>
        public static OperationEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type OperationEnum", value));

            return (OperationEnum) index;
        }
    }
} 