/*
 * Batchly.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Batchly.PCL;

namespace Batchly.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum OperatingSystemEnum
    {
        NONE, //TODO: Write general description for this method
        WINDOWS, //TODO: Write general description for this method
        UBUNTU, //TODO: Write general description for this method
        CENTOS, //TODO: Write general description for this method
        RHEL, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type OperatingSystemEnum
    /// </summary>
    public static class OperatingSystemEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "None", "Windows", "Ubuntu", "CentOS", "RHEL" };

        /// <summary>
        /// Converts a OperatingSystemEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The OperatingSystemEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(OperatingSystemEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case OperatingSystemEnum.NONE:
                case OperatingSystemEnum.WINDOWS:
                case OperatingSystemEnum.UBUNTU:
                case OperatingSystemEnum.CENTOS:
                case OperatingSystemEnum.RHEL:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of OperatingSystemEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of OperatingSystemEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<OperatingSystemEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into OperatingSystemEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed OperatingSystemEnum value</returns>
        public static OperatingSystemEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type OperatingSystemEnum", value));

            return (OperatingSystemEnum) index;
        }
    }
} 