/*
 * Batchly.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Batchly.PCL;

namespace Batchly.PCL.Models
{
    public class ProcessorModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string accountName;
        private string accountId;
        private RequestTypeEnum? requestType;
        private ResponseTypeEnum? responseType;
        private int? activeJobCount;
        private OpeartingSystemEnum? opeartingSystem;
        private DateTime? createdOn;
        private string description;
        private string logoLocation;
        private string id;
        private string name;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AccountName")]
        public string AccountName 
        { 
            get 
            {
                return this.accountName; 
            } 
            set 
            {
                this.accountName = value;
                onPropertyChanged("AccountName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AccountId")]
        public string AccountId 
        { 
            get 
            {
                return this.accountId; 
            } 
            set 
            {
                this.accountId = value;
                onPropertyChanged("AccountId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RequestType", ItemConverterType = typeof(StringValuedEnumConverter))]
        public RequestTypeEnum? RequestType 
        { 
            get 
            {
                return this.requestType; 
            } 
            set 
            {
                this.requestType = value;
                onPropertyChanged("RequestType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ResponseType", ItemConverterType = typeof(StringValuedEnumConverter))]
        public ResponseTypeEnum? ResponseType 
        { 
            get 
            {
                return this.responseType; 
            } 
            set 
            {
                this.responseType = value;
                onPropertyChanged("ResponseType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ActiveJobCount")]
        public int? ActiveJobCount 
        { 
            get 
            {
                return this.activeJobCount; 
            } 
            set 
            {
                this.activeJobCount = value;
                onPropertyChanged("ActiveJobCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OpeartingSystem", ItemConverterType = typeof(StringValuedEnumConverter))]
        public OpeartingSystemEnum? OpeartingSystem 
        { 
            get 
            {
                return this.opeartingSystem; 
            } 
            set 
            {
                this.opeartingSystem = value;
                onPropertyChanged("OpeartingSystem");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CreatedOn")]
        public DateTime? CreatedOn 
        { 
            get 
            {
                return this.createdOn; 
            } 
            set 
            {
                this.createdOn = value;
                onPropertyChanged("CreatedOn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LogoLocation")]
        public string LogoLocation 
        { 
            get 
            {
                return this.logoLocation; 
            } 
            set 
            {
                this.logoLocation = value;
                onPropertyChanged("LogoLocation");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 