/*
 * Batchly.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Batchly.PCL;

namespace Batchly.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum ResponseTypeEnum
    {
        NONE, //TODO: Write general description for this method
        DEFAULT, //TODO: Write general description for this method
        FILE, //TODO: Write general description for this method
        DB, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type ResponseTypeEnum
    /// </summary>
    public static class ResponseTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "None", "Default", "File", "Db" };

        /// <summary>
        /// Converts a ResponseTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The ResponseTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(ResponseTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case ResponseTypeEnum.NONE:
                case ResponseTypeEnum.DEFAULT:
                case ResponseTypeEnum.FILE:
                case ResponseTypeEnum.DB:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of ResponseTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of ResponseTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<ResponseTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into ResponseTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed ResponseTypeEnum value</returns>
        public static ResponseTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type ResponseTypeEnum", value));

            return (ResponseTypeEnum) index;
        }
    }
} 