/*
 * Batchly.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/19/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Batchly.PCL;

namespace Batchly.PCL.Models
{
    public class UpdateHadoopJobRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string projectId;
        private string clusterId;
        private string jarLocation;
        private string actionOnFailure;
        private List<string> instanceTypes;
        private string arguments;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ProjectId")]
        public string ProjectId 
        { 
            get 
            {
                return this.projectId; 
            } 
            set 
            {
                this.projectId = value;
                onPropertyChanged("ProjectId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ClusterId")]
        public string ClusterId 
        { 
            get 
            {
                return this.clusterId; 
            } 
            set 
            {
                this.clusterId = value;
                onPropertyChanged("ClusterId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("JarLocation")]
        public string JarLocation 
        { 
            get 
            {
                return this.jarLocation; 
            } 
            set 
            {
                this.jarLocation = value;
                onPropertyChanged("JarLocation");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ActionOnFailure")]
        public string ActionOnFailure 
        { 
            get 
            {
                return this.actionOnFailure; 
            } 
            set 
            {
                this.actionOnFailure = value;
                onPropertyChanged("ActionOnFailure");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("InstanceTypes")]
        public List<string> InstanceTypes 
        { 
            get 
            {
                return this.instanceTypes; 
            } 
            set 
            {
                this.instanceTypes = value;
                onPropertyChanged("InstanceTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Arguments")]
        public string Arguments 
        { 
            get 
            {
                return this.arguments; 
            } 
            set 
            {
                this.arguments = value;
                onPropertyChanged("Arguments");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 